# Lista de Exercícios da Semana 2

__Aluno:__ Guilherme Santos Silva

__1.__ Como importar a biblioteca numpy e verificar a versão atualizada?

Resposta: Para importar basta utilizar a função *import* e logo em seguida digitar numpy. E para verificar a versão mais atualizada basta colocar no prompt: import numpy / print numpy.__version__

__2.__ Explique, com suas palavras, os conceitos de vetorização e broadcasting que Nympy implementa.

Resposta: __Vetorização__ é o que nos permite aplicar uma função a um array em vez de aplicar uma função de elemento a elemento. Já o __Broadcasting__ se refere à capacidade do NumPy de tratar matrizes de diferentes formas durante as operações aritméticas que em geralmente são feitas em elementos correspondentes.

__3.__ Liste as diferenças entre uma lista, um dicionário, um array numpy, dando exemplos
de aplicação de em que cada tipo seria mais interessante.

Resposta: Tanto listas como arrays são objetos mais usados e têm como diferenças a performarce e funcionalidades disponíveis como também, no array todos os elemntos têm que ter o mesmo tipo de dados, e na lista pode ter elemntos de tipos diferentes. O dicionário é um tipo de coleção diferente pois ele é caracterizado como um tipo de mapeamento do python que é feito a partir de uma chave para atribuir um valor. Um exemplo de aplicação sobre as listas basta colocar seus intens em colchetes [] e separar cade elemento por uma vírgula. Ex:lista = ['x', 'y', 'z', '8',]; no caso do array é preciso importar o módulo ou pacote. Ex: >>>__import__ array __as__ ar; Já em dicionário é preciso começar com o dicionário vazio e adicionar pares chaves ao valor, nesse caso dicionário vazio é escrito de forma em chaves vazia {}. Ex: Determinar idioma que irá usar (nesse caso o inglês), eng2sp = {}.


__4.__ Forme a matriz
[[1, 6, 11],
[2, 7, 12],
[3, 8, 13],
[4, 9, 14],
[5, 10, 15]]
usando lista e array Numpy.

In [13]:
#Resposta:
import numpy as np

In [26]:
lista = [[1, 6, 11],
[2, 7, 12],
[3, 8, 13],
[4, 9, 14],
[5, 10, 15]]
print(lista)

[[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]]


In [27]:
np.array( lista )

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

__5.__ Usando numpy, crie:

(a) um vetor de 10 elementos entre 1 e 20

(b) um vetor entre 1 e 20, com passo de 2

(c) uma matriz 3x3 cujos elementos da diagonal sejam o vetor [1,2,3] e os demais
sejam todos 0.

In [37]:
#Resposta da letra a: 
np.random.randint(1,20,10)

array([ 3,  1,  1, 15, 14, 18,  9,  2, 15, 18])

In [59]:
#Resposta da letra b part.1:
a = np.arange(20)

In [62]:
#Resposta da letra b part.2:
a[1:20:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
#Resposta da letra c: 
np.diag ([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])